services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:latest
    container_name: postgres-yumm
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: unless-stopped

  # Redis 캐시
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend-network
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf

  # Spring Boot 백엔드
  backend:
    image: hyeonmin2/yummy-market:latest
    container_name: spring-backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: