version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:latest
    container_name: postgres-yumm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: yummy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    restart: unless-stopped

  # Redis 캐시
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Spring Boot 백엔드
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yummy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      # CORS 설정 추가 - 로컬 개발 서버 허용
      SPRING_CORS_ALLOWED_ORIGINS: http://localhost:3000
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: