server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yummy
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  data:
    redis:
      port: 6379
      host: localhost
      password: ${REDIS_PASSWORD}
jwt:
  secret: ${JWT_TOKEN}
  token-validity-in-seconds: 3600000